# Promise.withResolvers

## 提出问题

Promise 对于 JavaScript 来说太重要了，前端的同学估计没有哪一天不接触 Promise，JavaScript 的世界里异步无处不在。

Promise 解决了回调地狱的问题，还为 async await 的出现做了垫脚石。

但是大家每次在亲手创造一个 Promise 对象时，内心是否时常有一丝丝焦虑和憎恨：还要手写回调函数，resolve 想传出来还得再定义一个变量，恶心！或许你刚开始是抗拒的，但是后来接受了，习惯了。

这里我们把恶心的代码再次贴出来：

```js
// 多定义了两个变量，只是为了传递值
let resolve, reject;
const promise = new Promise((res, rej) => {
  // 还是要写恶心的回调函数
  resolve = res;
  reject = rej;
});
// 某个地方
resolve(data);

// 或者某个地方
reject(error);
```

你有没有写过这样恶心的代码？你肯定写过。

## 解决问题

这次的新特性 Promise.withResolvers，就是来解救我们的。

直接看代码示例：

```js
const { promise, resolve, reject } = Promise.withResolvers();
```

这就创造了一个新的 Promise 实例，而且把其对应的 resolve reject 方法也给出来了。

没有回调，不需要另设变量把 resolve 传出来。

这段代码和上面那段恶心的代码等价，大家对照一下，应该很快就理解了。

不过可能大家会认为 Promise.withResolvers 这个名字不太合适，有人提出应该叫 Promise.create。但是 Promise.withResolvers 返回的是一个普通对象（POJO），如果叫 Promise.create 的话，返回的应该是 Promise 实例更合适。关于名字问题有过很多争论，但是最终也没有定下一个更合适的名字，因此目前为止，还是叫 Promise.withResolvers。

## 浏览器支持情况

- 预计 2024 年正式发版。 目前主流浏览器还没有全部支持该特性
- 在 Chrome 119（发布于 2023 年 10 月 31 日）版本之后已可使用

## 语法解释

Promise.withResolvers() 静态方法返回一个对象，其包含一个新的 Promise 对象和两个函数，用于解决或拒绝它，对应于传入给 Promise() 构造函数执行器的两个参数。

```js
const { promise, resolve, reject } = Promise.withResolvers();
```

参数

- 无

返回值包含以下属性的普通对象：

- promise：一个 Promise 对象。
- resolve：一个函数，用于解决该 Promise。关于其语义，请参阅 Promise() 构造函数。
- reject：一个函数，用于拒绝该 Promise。关于其语义，请参阅 Promise() 构造函数。

Promise.withResolvers() 完全等同于以下代码：

```js
let resolve, reject;
const promise = new Promise((res, rej) => {
  resolve = res;
  reject = rej;
});
```

只是它更简洁，并且不需要使用 let。

使用 Promise.withResolvers() 关键的区别在于解决和拒绝函数现在与 Promise 本身处于同一作用域，而不是在执行器中被创建和一次性使用。这可能使得一些更高级的用例成为可能，例如在重复事件中重用它们，特别是在处理流和队列时。这通常也意味着相比在执行器内包装大量逻辑，嵌套会更少。

Promise.withResolvers() 是通用的且支持子类化，这意味着它可以在 Promise 的子类上调用，结果将包含一个该子类类型的 promise。要做到这一点，子类的构造函数必须实现与 Promise() 构造函数相同的签名——接受一个单独的 executor 函数，该函数可以用 resolve 和 reject 回调作为参数来调用。

## Polyfill

该特性要实现 Polyfill 并不复杂，core-js 已经有 Polyfill 了。大家完全可以先用起来。

```js
Promise.withResolvers = function () {
  let resolver, reject;
  const promise = new Promise((rs, rj) => {
    resolver = rs;
    reject = rj;
  });
  return { promise, resolver, reject };
};
```

### 有意思的特性

MDN 上还给出了一个非常有意思的特性，请看示例代码

```js
class NotPromise {
  constructor(executor) {
    // executor中传入的两个方法会分别传给返回的`resove`和`reject`变量
    executor(
      (value) => console.log("Resolved", value),
      (reason) => console.log("Rejected", reason)
    );
  }
}

const { promise, resolve, reject } = Promise.withResolvers.call(NotPromise);
resolve("hello");
// 打印: Resolved hello
```

例子中通过 call 方法，用 NotPromise 替换掉了 Promise。 call 是函数实例的一个方法，可以改变函数中 this 的指向。

NotPromise 虽然不是 Promise 类，但是可以模拟 Promise 构造函数的结构。

Promise 构造函数接受一个函数作为参数，在这里对应的就是 executor 函数，Promise 构造函数会去调用这个函数，并传入两个参数，分别是 resolve 函数和 reject 函数。

NotPromise 只要能模拟上面 Promise 做的事情，就可以用来代替 Promise。只是这时的 resolve 和 reject 也已经被代替，不再具有 Promise 的功能。

这里最终返回的 resolve 和 reject 分别就是 executor 函数传入的两个函数参数。

这里最终返回的 promise 对象是 NotPromise 的实例。

所以整个代码只是借用了 Promise 的形式，和 Promise 的功能本身已经毫无关系了。

目前还看不出这样的功能有什么用处，或许哪天就有用了。

## 更多

你可能还了解过一些相关概念，比如 defer、deferred。它们的实现都是类似的，你可以在 react 代码库、vue 代码库、vite 代码库 和 axios 代码库 见到它们。

<table>
    <thead>
        <tr>
            <th>Library</th>
            <th>Example</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>React</td>
            <td><a href="https://github.com/facebook/react/blob/d9e0485c84b45055ba86629dc20870faca9b5973/packages/react-dom/src/__tests__/ReactDOMFizzStaticBrowser-test.js#L95">inline example</a></td>
        </tr>
        <tr>
            <td>Vue</td>
            <td><a href="https://github.com/vuejs/core/blob/9c304bfe7942a20264235865b4bb5f6e53fdee0d/packages/runtime-core/src/compat/componentAsync.ts#L32">inline example</a></td>
        </tr>
        <tr>
            <td>Axios</td>
            <td><a href="https://github.com/axios/axios/blob/bdf493cf8b84eb3e3440e72d5725ba0f138e0451/lib/cancel/CancelToken.js#L20">inline example</a></td>
        </tr>
        <tr>
            <td>TypeScript</td>
            <td><a href="https://github.com/microsoft/TypeScript/blob/1d96eb489e559f4f61522edb3c8b5987bbe948af/src/harness/util.ts#L121">utility</a></td>
        </tr>
        <tr>
            <td>Vite</td>
            <td><a href="https://github.com/vitejs/vite/blob/134ce6817984bad0f5fb043481502531fee9b1db/playground/test-utils.ts#L225">inline example</a></td>
        </tr>
        <tr>
            <td>Deno stdlib</td>
            <td><a href="https://deno.land/std@0.178.0/async/deferred.ts?source" rel="nofollow">utility</a></td>
        </tr>
    </tbody>
</table>

## 示例一：可取消计时器

某些情况下需要在 Promise 外部获取 resolve 和 reject 句柄，我们通常会这么编写代码

```js
function cancelableTimeout(ms) {
  let cancelTimeout;
  const promise = new Promise((resolve, reject) => {
    const timeoutId = setTimeout(resolve, ms);
    cancelTimeout = () => {
      clearTimeout(timeoutId);
      reject(new Error("The timeout was canceled."));
    };
  });

  return { promise, cancelTimeout };
}
```

有了 Promise.withResolvers 之后，我们的代码会简洁很多

```js
function cancelableTimeout(ms) {
  const { promise, resolve, reject } = Promise.withResolvers();

  const timeoutId = setTimeout(resolve, ms);
  const cancelTimeout = () => {
    clearTimeout(timeoutId);
    reject(new Error("The timeout was canceled."));
  };

  return { promise, cancelTimeout };
}
```

再者：

```js
let resolve, reject;
const promise = new Promise((res, rej) => {
  resolve = res;
  reject = rej;
});
Math.random() > 0.5 ? resolve("ok") : reject("not ok");
```

现在：

```js
const { promise, resolve, reject } = Promise.withResolvers();
Math.random() > 0.5 ? resolve("ok") : reject("not ok");
```

## 示例二：request 中使用

```js
function myRequest(config) {
  let resolve;
  let reject;
  const promise = new Promise((_resolve, _reject) => {
    // 提取 resolve 和 reject 在别处使用
    resolve = _resolve;
    reject = _reject;
  });
  request(config, (response) => {
    const buffer = [];
    response.on("data", (data) => buffer.push(data));
    response.on("end", () => resolve(buffer)); // 在这里使用 resolve
    response.on("error", (reason) => reject(reason)); // 在这里使用 reject
  });
  return promise;
}
```

现在：

```js
function myRequest(config) {
  const { promise, resolve, reject } = Promise.withResolvers();
  request(config, (response) => {
    const buffer = [];
    response.on("data", (data) => buffer.push(data));
    response.on("end", () => resolve(buffer));
    response.on("error", (reason) => reject(reason));
  });
  return promise;
}
```

## 示例三：socket 中使用

```js
let resolve = () => {};
let reject = () => {};

function request(type, message) {
  if (socket) {
    const promise = new Promise((res, rej) => {
      resolve = res;
      reject = rej;
    });
    socket.emit(type, message);
    return promise;
  }

  return Promise.reject(new Error("Socket unavailable"));
}

socket.on("response", (response) => {
  if (response.status === 200) {
    resolve(response);
  } else {
    reject(new Error(response));
  }
});

socket.on("error", (err) => {
  reject(err);
});
```

现在：

```js
const { promise, resolve, reject } = Promise.withResolvers();
function request(type, message) {
  if (socket) {
    socket.emit(type, message);
    return promise;
  }
  return reject(new Error("Socket unavailable"));
}
socket.on("response", (response) => {
  if (response.status === 200) resolve(response);
  else reject(new Error(response));
});
socket.on("error", (err) => reject(err));
```

## 示例四：将流转换为异步可迭代对象

Promise.withResolvers() 的使用场景是，当你有一个 promise，需要通过无法包装在 promise 执行器内的某个事件监听器来解决或拒绝。以下示例将 Node.js 的可读流转换为异步可迭代对象。这里的每个 promise 代表一个可用的数据批次，每次读取当前批次时，就会为下一个批次创建一个新的 promise。请注意，事件监听器只附加了一次，但实际上每次都调用了不同版本的 resolve 和 reject 函数。

```js
async function* readableToAsyncIterable(stream) {
  let { promise, resolve, reject } = Promise.withResolvers();
  stream.on("error", (error) => reject(error));
  stream.on("end", () => resolve());
  stream.on("readable", () => resolve());

  while (stream.readable) {
    await promise;
    let chunk;
    while ((chunk = stream.read())) {
      yield chunk;
    }
    ({ promise, resolve, reject } = Promise.withResolvers());
  }
}
```

## 示例五：在非 Promise 构造函数上调用 withResolvers()

Promise.withResolvers() 是一个通用方法。它可以在任何实现了与 Promise() 构造函数相同签名的构造函数上调用。例如，我们可以在一个将 console.log 作为 resolve 和 reject 函数传入给 executor 的构造函数上调用它：

```js
class NotPromise {
  constructor(executor) {
    // “resolve”和“reject”函数的行为与原生 Promise 完全不同，但 `Promise.resolve()` 方法以相同的方式调用它们。
    executor(
      (value) => console.log("已解决", value),
      (reason) => console.log("已拒绝", reason),
    );
  }
}

Promise.resolve.call(NotPromise, "foo"); // 输出 "已解决 foo"
```

展平嵌套的 thenable 对象的能力是由 Promise() 构造函数的 resolver 函数实现的，因此如果你在另一个构造函数上调用它，嵌套的 thenable 对象可能不会被展平，这取决于该构造函数如何实现其 resolver 函数。

```js
const thenable = {
  then(onFulfilled, onRejected) {
    onFulfilled({
      // 该 thenable 对象将兑现为另一个 thenable 对象
      then(onFulfilled, onRejected) {
        onFulfilled(42);
      },
    });
  },
};

Promise.resolve.call(NotPromise, thenable); // 输出 "已兑现 { then: [Function: then] }"
```

## 链接

- https://github.com/tc39/proposal-promise-with-resolvers
- https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers
